<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\UKHO.ADDS.EFS.Infrastructure\Configuration\Namespaces\ProcessNames.cs" Link="Configuration\Namespaces\ProcessNames.cs" />
    <Compile Include="..\UKHO.ADDS.EFS.Infrastructure\Configuration\Namespaces\ServiceConfiguration.cs" Link="Configuration\Namespaces\ServiceConfiguration.cs" />
    <Compile Include="..\UKHO.ADDS.EFS.Infrastructure\Configuration\Namespaces\StorageConfiguration.cs" Link="Configuration\Namespaces\StorageConfiguration.cs" />
    <Compile Include="..\UKHO.ADDS.EFS.Infrastructure\Configuration\Orchestrator\BuilderEnvironmentVariables.cs" Link="Orchestrator\BuilderEnvironmentVariables.cs" />
    <Compile Include="..\UKHO.ADDS.EFS.Infrastructure\Configuration\Orchestrator\GlobalEnvironmentVariables.cs" Link="Orchestrator\GlobalEnvironmentVariables.cs" />
    <Compile Include="..\UKHO.ADDS.EFS.Infrastructure\Retries\HttpClientPolicyLogger.cs" Link="Retries\HttpClientPolicyLogger.cs" />
    <Compile Include="..\UKHO.ADDS.EFS.Infrastructure\Retries\HttpRetryPolicyFactory.cs" Link="Retries\HttpRetryPolicyFactory.cs" />
    <Compile Include="..\UKHO.ADDS.EFS.Infrastructure\Services\TemplateFileNameGeneratorService.cs" Link="Services\TemplateFileNameGeneratorService.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Polly" Version="8.7.0" />
    <PackageReference Include="Aspire.Azure.Data.Tables" Version="9.5.2" />
    <PackageReference Include="Aspire.Azure.Storage.Queues" Version="9.5.2" />
    <PackageReference Include="Aspire.Azure.Storage.Blobs" Version="9.5.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\UKHO.ADDS.EFS.Domain.Services\UKHO.ADDS.EFS.Domain.Services.csproj" />
  </ItemGroup>

</Project>
