<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

 <ItemGroup>
  <InternalsVisibleTo Include="UKHO.ADDS.EFS.Infrastructure.UnitTests" />
  <InternalsVisibleTo Include="DynamicProxyGenAssembly2" />
</ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.17" />
    <PackageReference Include="Microsoft.Extensions.Telemetry.Abstractions" Version="10.7.0" />
    <PackageReference Include="Microsoft.Identity.Web" Version="4.14.0" />
    <PackageReference Include="Polly" Version="8.7.0" />
    <PackageReference Include="Aspire.StackExchange.Redis.DistributedCaching" Version="9.5.2" />
    <PackageReference Include="Azure.Storage.Blobs" Version="12.29.1" />
    <PackageReference Include="Aspire.Azure.Data.Tables" Version="9.5.2" />
    <PackageReference Include="Aspire.Azure.Storage.Queues" Version="9.5.2" />
    <PackageReference Include="Aspire.Azure.Storage.Blobs" Version="9.5.2" />
    <PackageReference Include="Azure.Messaging.EventHubs" Version="5.12.2" />
    <PackageReference Include="Konscious.Security.Cryptography.Blake2" Version="1.1.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\configuration\UKHO.ADDS.Aspire.Configuration\UKHO.ADDS.Aspire.Configuration.csproj" />
    <ProjectReference Include="..\UKHO.ADDS.EFS.Domain.Services\UKHO.ADDS.EFS.Domain.Services.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="UKHO.ADDS.EFS.Infrastructure.UnitTests" />
  </ItemGroup>

</Project>
