parameters:
# The name of the environment to be used in Azure DevOps.
- name: AzureDevOpsEnvironment
  type: string
# Used to generate job names and, in lower case, to select the correct var/x-deploy.yml variable file.
- name: ShortName
  type: string
# If true, additional debugging will be enabled.
- name: AdditionalDebugging
  type: boolean
  default: false

jobs:
- deployment: ${{ parameters.ShortName }}DeployResources
  displayName: "${{ upper(parameters.ShortName) }} - deploy resources"
  environment: ${{ parameters.AzureDevOpsEnvironment }}
  workspace:
    clean: all
  variables:
  - template: var/${{ lower(parameters.ShortName) }}-deploy.yml
  strategy:
    runOnce:
      deploy:
        steps:
        - checkout: self
          clean: true
          submodules: true

        - download: none

        - task: AzureCLI@2
          displayName: Check Key Vault Secrets Officer role
          inputs:
            azureSubscription: ${{ variables.AzureSubscription }}
            workingDirectory: $(Build.SourcesDirectory)
            scriptType: bash
            scriptLocation: inlineScript
            inlineScript: |
              roleExists=$(az role assignment list --scope /subscriptions/$AZURE_SUBSCRIPTION_ID --role b86a8fe4-44ce-4948-aee5-eccb2c155cd7 --assignee $PIPELINE_CLIENT_OBJECT_ID --query "[] | length(@)")

              if [ "$roleExists" -eq "0" ]; then
                echo "Assigning 'Key Vault Secrets Officer' role to pipeline client principal..."
                az role assignment create --assignee-object-id $PIPELINE_CLIENT_OBJECT_ID --role b86a8fe4-44ce-4948-aee5-eccb2c155cd7 --scope /subscriptions/$AZURE_SUBSCRIPTION_ID
              else
                echo "'Key Vault Secrets Officer' role already assigned to pipeline client principal, skipping assignment"
              fi
          env:
            PIPELINE_CLIENT_OBJECT_ID: $(PIPELINE-CLIENT-OBJECT-ID)
            AZURE_SUBSCRIPTION_ID: $(AZURE_SUBSCRIPTION_ID)

        - task: AzureCLI@2
          displayName: Deploy permanent infrastructure
          inputs:
            azureSubscription: ${{ variables.AzureSubscription }}
            workingDirectory: $(Build.SourcesDirectory)
            scriptType: bash
            scriptLocation: inlineScript
            inlineScript: |
              set -e
              echo "Deploying resources..."
              DEPLOY_SECONDS=$EPOCHSECONDS
              DEPLOYMENT_NAME=$AZURE_ENV_NAME-retain-$DEPLOY_SECONDS
              export PIPELINE_DEPLOYMENT_NAME=$AZURE_ENV_NAME-pipeline-roles-$DEPLOY_SECONDS
              cd "$(Build.SourcesDirectory)/infra-retain"

              if [ "${{ parameters.AdditionalDebugging }}" == "True" ]; then
                echo "Current environment variables:"
                echo "--------------------------------------------------------------------------------"
                env | sort
                echo "--------------------------------------------------------------------------------"
                az deployment sub create --name $DEPLOYMENT_NAME --location $AZURE_LOCATION --no-prompt --parameters main.bicepparam --debug
              else
                az deployment sub create --name $DEPLOYMENT_NAME --location $AZURE_LOCATION --no-prompt --parameters main.bicepparam
              fi
          env:
            PIPELINE-CLIENT-OBJECT-ID: $(PIPELINE-CLIENT-OBJECT-ID)

        - template: get-infrastructure-details.yml
          parameters:
            AzureSubscription: ${{ variables.AzureSubscription }}
