<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Microsoft.Extensions.Configuration.AzureAppConfiguration" Version="9.5.2-preview.1.25522.3" />
    <PackageReference Include="UKHO.ADDS.Infrastructure.Serialization" Version="0.0.60217-alpha.1" />
    <PackageReference Include="OpenTelemetry.Api" Version="1.15.3" />
    <PackageReference Include="Serilog" Version="4.3.1" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="UKHO.ADDS.Aspire.Configuration.Seeder" />
    <InternalsVisibleTo Include="UKHO.ADDS.Aspire.Configuration.Seeder.Tests" />
  </ItemGroup>

</Project>
